FROM node:latest

WORKDIR /usr/src/app

COPY yarn.lock ./
COPY package.json ./
COPY lerna.json ./

RUN npx lerna bootstrap

# Install modules for nodes
COPY ./packages/nodes/package.json /usr/src/app/packages/nodes/package.json
RUN yarn

# Install modules for server
COPY ./packages/server/package.json /usr/src/app/packages/server/package.json
RUN yarn

COPY ./packages/nodes /usr/src/app/packages/nodes
WORKDIR /usr/src/app/packages/nodes
RUN yarn build

COPY ./packages/server /usr/src/app/packages/server
WORKDIR /usr/src/app/packages/server

CMD [ "yarn", "dev" ]
